export const geographyData = [
	{
		question: ' Które z poniższych państw ma dostęp do morza?',
		a: 'Luksemburg',
		b: 'Macedonia',
		c: 'Serbia',
		d: 'Słowenia',
		img: './../img/quizData/geography1.jpg',
		correct: 'd',
	},
	{
		question: 'Które morze ma największe zasolenie wód?',
		a: 'Adriatyckie',
		b: 'Karaibskie',
		c: 'Czerwone',
		d: 'Koralowe',
		img: './../img/quizData/geography2.jpg',
		correct: 'c',
	},
	{
		question: 'Który kraj ma najdłuższą linię brzegową na świecie?',
		a: 'Rosja',
		b: 'Indonezja',
		c: 'Kanada',
		d: 'USA',
		img: './../img/quizData/geography3.jpg',
		correct: 'c',
	},
	{
		question: 'Jakiego koloru nie znajdziesz w nazwie żadnego morza?',
		a: 'Żółtego',
		b: 'Czarnego',
		c: 'Białego',
		d: 'Niebieskiego',
		img: './../img/quizData/geography4.jpg',
		correct: 'd',
	},
]

export const mathData = [
	{
		question: 'Jakie jest pole powierzchni kwadratu o boku długości 5 cm?',
		a: '25 cm',
		b: '10 cm^2',
		c: '25 cm^2',
		d: '20 cm^2',
		img: './../img/quizData/math1.jpg',
		correct: 'c',
	},
	{
		question: 'Jaki jest pierwiastek kwadratowy z liczby 144?',
		a: '77',
		b: '12',
		c: '14',
		d: '44',
		img: './../img/quizData/math2.jpg',
		correct: 'b',
	},
	{
		question: 'Ile wynosi iloczyn 4 i 9?',
		a: '26',
		b: '5',
		c: '13',
		d: '36',
		img: './../img/quizData/math3.jpg',
		correct: 'd',
	},
	{
		question: 'Jaka jest różnica między 13 a 8?',
		a: '5',
		b: '13',
		c: '8',
		d: '1',
		img: './../img/quizData/math4.jpg',
		correct: 'a',
	},
	{
		question: 'Jaka jest wartość ćwierć tony (1/4) wyrażona w gramach?',
		a: '2500g',
		b: '25 000 g',
		c: '250 000 g',
		d: '2 500 000g',
		img: './../img/quizData/math5.jpg',
		correct: 'c',
	},
]

export const itData = [
	{
		question: 'Do czego używany jest protokół SMTP?',
		a: 'Przesyłania plików pomiędzy komputerami',
		b: 'Surfowania w sieci',
		c: 'Wysyłania poczty e-mail',
		d: 'Odczytywania daty i godziny',
		img: './../img/quizData/it1.jpg',
		correct: 'c',
	},
	{
		question: 'Co oznacza skrót "WWW"?',
		a: 'Wide World Web',
		b: 'World Wide Web',
		c: 'Whole World Web',
		d: 'Web Wide World',
		img: './../img/quizData/it2.jpg',
		correct: 'b',
	},
	{
		question: 'Co zaliczamy do urządzeń peryferyjnych komputera?',
		a: 'HDD, SSD i Pendrive',
		b: 'Klawiaturę, skaner, myszkę',
		c: 'Płytę główną, drukarkę, procesor',
		d: 'Żadne z powyższych',
		img: './../img/quizData/it3.jpg',
		correct: 'b',
	},
	{
		question: 'Co robi klawisz "HOME", który znajduje się na klawiaturze PC?',
		a: 'Przenosi na stronę główną',
		b: 'Odświeża. pulpit',
		c: 'Przenosi na górę strony',
		d: 'Otwiera pasek START',
		img: './../img/quizData/it4.jpg',
		correct: 'c',
	},
	{
		question: 'Która wartość jest największa?',
		a: '10 000 MB',
		b: '10 GB',
		c: '100 GB',
		d: '1 TB',
		img: './../img/quizData/it1.jpg',
		correct: 'd',
	},
]

export const musicData = [
	{
		question: 'Jak na początku brzmiała nazwa zespołu "Maanam"?',
		a: 'Blues Maanam Distortion',
		b: 'Czas na Maanam',
		c: 'Fala Dźwięków Maanam',
		d: 'Maanam Elektryczny Prysznic',
		img: './../img/quizData/music1.jpg',
		correct: 'd',
	},
	{
		question: 'W jakim mieście został założony zespół Bajm?',
		a: 'w Lublinie',
		b: 'w Płocku',
		c: 'w Warszawie',
		d: 'w Zielonej Górze',
		img: './../img/quizData/music2.jpg',
		correct: 'a',
	},
	{
		question: 'Sidney Polak, czyli autor piosenki "Otwieram wino" znany jest także jako...?',
		a: 'Brat Pezeta',
		b: 'Gitarzysta zespołu Myslovitz',
		c: 'Perkusista zespołu T. Love',
		d: 'Manager zespołu Kombi',
		img: './../img/quizData/music3.jpg',
		correct: 'c',
	},

	{
		question: 'Jak na imię ma Kayah?',
		a: 'Krystyna',
		b: 'Julia',
		c: 'Katarzyna',
		d: 'Ewelina',
		img: './../img/quizData/music4.jpg',
		correct: 'c',
	},
	{
		question: ' Który gitarzysta nagrał solo do utworu Michaela Jacksona "Beat It"?',
		a: 'Van Halen',
		b: 'Carlos Santana',
		c: 'Slash',
		d: 'Jimmy Page',
		img: './../img/quizData/music5.jpg',
		correct: 'a',
	},
]
